main: US.Siiant.DefinedGenerator.DefinedGenerator
name: DefaultGenerator
version: 1.0
api-version: 1.16
author: Siiant
description: Lets you define a generator.
commands:
  DefinedGenerator:
    aliases: dg